### ISSUE TITLE
~ path doesn't work

### ISSUE THREAD

**Issue by jongbeau** [ddelbondio/ruby-sass-loader#2]
Other loaders (like sass-loader) support using the ~ to reference node_modules in the import path. Ruby sass loader does not seem to recognize this.

@import('~bootstrap-sass')

**Comment by ddelbondio** [comment]
I don't think this can be supported. sass-loader is using webpacks resolving mechanism for this to work. But since we hand off the compilation to the ruby process, we can't intercept the imports from the loader. The only way would be to write an sass plugin in ruby which supports this special syntax. This is out of the scope for this loader and should be done in an ruby package if needed.
